
EXP_NAME : "test_singleconv_trilinearUpsample_unnorm_mse" #EXP_NAME used to distinguish each run
OUT: "out" #path to output directory
SYSTEM:
  e5: False #control dataset_path to use on cluster or loacl
  DEVICE: cuda
  GPU_IDS: 0
  NUM_GPUS: 1
  NUM_CPUS: 2
MODEL:
  INPUT_SIZE: [ 128, 128, 128 ]
  ARCHITECTURE: autoencoder
  BLOCK_TYPE: single 
  FILTERS: [32,64,96,112,128]
  IN_PLANES: 1
  OUT_PLANES: 1 
  PAD_MODE: 'reflect'
  ACT_MODE: 'elu'
  NORM_MODE: 'gn'
  UPSAMPLE_INTERP: True #whether use linear_interpolation to upsample 
LOSS:
  #####for reconstruntion loss
  name: mse
  #####for contrastive loss, not used yet
  n_views: 2
  temperature: 0.07
TRAINER:
  name: 'trainer' #Trainer to choose
  save_every: 50 #save frequency
  epoch: 5000
  fp16: False 
SOLVER:
  LR_SCHEDULER_NAME: "cosine"
  NAME: "adam"
  LR_START: 5e-4
  LR_END: 1e-6
  WEIGHT_DECAY: 0.0
  LR_WARMUP: 10
DATASET:
  name: 'visor_3d_dataset'
  batch_per_gpu: 8
  num_workers: 0
  shuffle: True
  ######for fixed dataset######
  data_path_dir: "/home/confetti/mnt/data/processed/t1779/100roi"
  e5_data_path_dir: "/share/home/shiqiz/data/t1779/100roi"
  ######for random generated dataset, not used here ######
  amount: 1000   #total amount of training data , only valid for radom_generated dataset
  raw_internal_path: "/home/confetti/data/mousebrainatlas/T11.ims.h5" 
  label_internal_path: "/home/confetti/data/mousebrainatlas/new_t11/registered_atlas.tiff"
  level: 0
  voxel_size: 4 #(um)
  min_valid_texture_length:  48 #(um)
  channel: 3
  zoom_factor: 6.25
  input_size: [128,128,128]
  IS_ISOTROPIC: True 
PREPROCESS:
  # only when NORM is True, NORM_MODE will func
  NORM: False 
  NORM_MODE: "min_max"
  # used to clip the data
  # for 100roi dataset, 96 is the global_min value, 2672 is the 99 percentile global_high value, to exclude some extra high value in data
  clip_low : 96 
  clip_high : 2672


